x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:

  django:
    container_name: "django"
    build: "."
    restart: unless-stopped
    entrypoint: './entry.sh'
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - "./db.sqlite3:/home/django/db.sqlite3"
      - "./mediafiles/:/home/django/mediafiles/"

  smtp4dev:
    container_name: "smtp4dev"
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - smtp4dev-data:/smtp4dev

  celery_broker:
    container_name: 'celery_broker'
    image: 'redis:7.4'
    ports:
      - '6379:6379'

  celery:
    container_name: "celery"
    build: '.'
    entrypoint: './celery_entry.sh'
    env_file:
      - ./.env
    volumes:
      - "./db.sqlite3:/home/django/db.sqlite3"
      - "./mediafiles/:/home/django/mediafiles/"
    depends_on:
      - 'celery_broker'
      - 'django'



  celery_beat:
    container_name: "celery_beat"
    build: '.'
    entrypoint: './celery_beat_entry.sh'
    env_file:
      - ./.env
    volumes:
      - "./db.sqlite3:/home/django/db.sqlite3"
      - "./mediafiles/:/home/django/mediafiles/"
    depends_on:
      - 'celery_broker'
      - 'django'
      - 'celery'

  redis_cache:
    container_name: "redis_cache"
    image: 'redis:7.4'
    ports:
      - '6388:6379'

volumes:
  smtp4dev-data:
