x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - "./.ci/nginx/conf.d:/etc/nginx/conf.d"
      - "./mediafiles/:/usr/nginx/mediafiles/"
      - "./staticfiles/:/usr/nginx/staticfiles/"
    ports:
      - "${NGINX_PORT}:15520"

  django:
    container_name: "django"
    build: "."
    restart: unless-stopped
    entrypoint: './entry.sh'
    env_file:
      - ./.env
    volumes:
      - "./mediafiles/:/home/django/mediafiles/"
      - "./staticfiles/:/home/django/staticfiles/"

  django_db:
    container_name: 'django_db'
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"

  celery_broker:
    container_name: 'celery_broker'
    image: 'redis:7.4'

  celery:
    container_name: "celery"
    build: '.'
    entrypoint: './celery_entry.sh'
    env_file:
      - ./.env
    volumes:
      - "./mediafiles/:/home/django/mediafiles/"
      - "./staticfiles/:/home/django/staticfiles/"
    depends_on:
      - 'celery_broker'
      - 'django'

  celery_beat:
    container_name: "celery_beat"
    build: '.'
    entrypoint: './celery_beat_entry.sh'
    env_file:
      - ./.env
    volumes:
      - "./mediafiles/:/home/django/mediafiles/"
      - "./staticfiles/:/home/django/staticfiles/"
    depends_on:
      - 'celery_broker'
      - 'django'
      - 'celery'

  redis_cache:
    container_name: "redis_cache"
    image: 'redis:7.4'
